config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  #get 'logout' => 'sessions#destroy', :as =>'logout'
  get 'login' => 'sessions#new', :as =>'login'
  get 'signup' => 'users#new', :as => 'signup'

  get '/home' => 'home#index'
  post '/check' => 'home#check'

  resources :cards
  resources :users
  resources :sessions

  get '/auth/:provider/callback', to: "sessions#create"
  delete 'logout', to: "sessions#destroy", as: 'logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  #attr_accessor :image
  #belongs_to :user
  belongs_to :deck
  validates :original_text, :translated_text, :presence => true
  before_validation :ensure_original_text_has_a_value
  validate :original_text_and_translated_text_validation
  validates_uniqueness_of :original_text, :case_sensitive => false
  before_create :set_review_date
  mount_uploader :image, CardUploader
    def set_review_date
      self.review_date = Date.today + 3.days
    end
 
  protected
    def ensure_original_text_has_a_value
      if original_text.nil?
        self.original_text = translated_text unless translated_text.blank?
      end
    end
  
    def original_text_and_translated_text_validation
        if self.original_text == self.translated_text
            errors.add( :base, "Original text must be different from Translated text") 
        end
    end  

scope :random_card, ->{ where('review_date <=?', Date.today).order('RANDOM()').limit(1) }  
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  #attr_accessible :email, :password, :password_confirmation
  validates_confirmation_of :password
  #validates_presence_of :password, :on =>:create
  #validates_presence_of :email
  #validates_uniqueness_of :email
  
  #has_many :cards
  has_many :decks
  belongs_to :current_deck, class_name: "Deck"

  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  end 

  def self.create_user_from_omniauth(auth)
    create(
      provider: auth['provider'],
      uid: auth['uid'],
      name: auth['info']['name']
    )
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base #.helper_method :current_user
  protect_from_forgery with: :exception
  before_action :require_login
  
  def not_authenticated
    redirect_to login_url, :alert => "Please login to access this page" if current_user.nil?
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  #before_filter :require_login, :only => :cards
  #before_filter :authenticate_user!
  #before_filter :not_authenticated

  def index
  	#@cards = Card.all
    @cards = current_user.cards.all
  end

  def show
  end

  def new
    #@card = Card.new
    @card = current_user.cards.new
  end

  def create
    #@card = Card.new(card_params)
    @card = current_user.cards.new(card_params)
 
   if @card.save
     redirect_to card_path(@card)
   else
     render 'new'
   end
  end

  def edit 
  end

  def update
    #@card = Card.find(params[:id])
    @card = current_user.cards.find(params[:id])

    if @card.update(card_params)
      redirect_to @card
    else
      render 'edit'
    end
  end

  def destroy
    #@card = Card.find(params[:id])
    @card = current_user.cards.find(params[:id])
    @card.destroy
    redirect_to :cards, flash: { notice: t('Card is successfully deleted') }
  end
 
  def set_card
  #@card = Card.find(params[:id])
  @card = current_user.cards.find(params[:id])
  end

private
  def card_params
    params.require(:card).permit(:original_text, :translated_text, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_auth

  def index
    @card = current_user.cards.random_card.first
  end

  def check
    result = Trainer.call(
      card_id: params[:card_id],
      original_text: params[:q],
      user: current_user 
    )
    redirect_to root_path, notice: result.notice
  end

  private
  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login
  
  def new
  end

  def create
    auth = request.env['omniauth.auth']
    session[:omniauth] = auth.except('extra')
    user = User.sign_in_from_omniauth(auth)
    session[:user_id] = user.id
    @current_user = User.find(session[:user_id])
    redirect_to root_url, :notice =>'Signed in successfully'
    #user = login(params[:email], params[:password], params[:remember_me])
    #if user
      #redirect_back_or_to root_url, :notice =>'Logged in successfully'
    #else
      #flash.now.alert = 'Invalid email or password'
      #render 'new'
    #end

    #user = User.where(email: params[:email]).first
      #if user && user.authenticate(params[:password])
        #session[:user_id] = user.id
        #redirect_to root_url, :notice => "You signed in successfully"
      #else
        #flash.now.alert = "Invalid email or password"
        #render 'new'
      #end
      
      #Omniauth
      #auth = requires.env['omniauth.auth']
      #session[:omniauth] = auth.expect('extra')
      #user = User.sign_in_from_omniauth(auth)
      #
  end

  def destroy
    logout
    session[:omniauth] = nil
    redirect_to root_url, :notice =>'Logged out successfully'
  end

  def failure
    redirect_to root_url, :alert =>'Authentication failed, please try again'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #has_secure_password validations: false

  def index
    #render 'show'
  end

  def new
    @user = current_user.new
  end

  def show
  end

  def create
    @user = current_user.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice =>"Signed up successfully"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      flash[:success] = "Profile successfully updated"
      redirect_to current_user
    else
      render 'edit'
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
    #params.require(:user).permit(:email, :salt, :encrypted_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for @card, :html => {:multipart => true} do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, "error") %> prohibited
        this card from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :original_text %><br>
    <%= f.text_field :original_text %>
  </p>
 
  <p>
    <%= f.label :translated_text %><br>
    <%= f.text_area :translated_text %>
  </p>

  <p>
    <%= f.file_field :image %><br>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cards/edit.html.erb
<h1>Edit Card</h1>
 
<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>All cards</h1>

<%= link_to "Add New Card", new_card_path %>

<ul>
	<% @cards.each do |card| %>
		<li> <%= card.original_text %></li>
    <td><%= link_to 'Show', card %></td>
    <td><%= link_to 'Edit', edit_card_path(card.id)%></td>
    <td><%= link_to 'Destroy', card,
            method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</ul>

app/views/cards/new.html.erb
<h1>Create a New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<h1>Cards:</h1>

<section>
      <p style="font-size: 28px;">
      <li> <%= @card.original_text  %></li>
      <li> <%= @card.translated_text %></li>
      <li> <%= @card.review_date %></li>
      <li> <%= image_tag @card.image.thumb.url if @card.image? %></li>
      </p>
</section>

 <%= link_to 'Edit', edit_card_path(@card) %> 
 <%= link_to 'Back', cards_path %>

app/views/home/index.html.erb
    <section>
      <p style="font-size: 22px;">
        Первый в мире удобный менеджер флеш-карточек. Именно так.
      </p>
    </section>

    <% if @card.nil? %>
      <section>
        <p>There is no card for check</p>
      </section>
    <% else %>
       <section>
      <p style="font-size: 28px;">
      <%= @card.translated_text %>
      </p>
    </section>

<%= form_tag('/check', method: "post") do %>
  <%= label_tag(:q, "Original Text") %><br>
  <%= text_field_tag(:q) %><br>
  <%= hidden_field_tag "card_id", @card.id %>
  <%= hidden_field_tag "user", current_user %>
  <br><p><%= image_tag @card.image.thumb.url if @card.image? %></p>
  <br><%= submit_tag("Check") %>
<% end %>
    <% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

<body>

  <% #Onmiauth %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <h1><%= link_to root_path do %>Flashcards<% end %></h1>
      </div>
      <div class="nav navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>Signed in as: <%= current_user.name %> - <%= image_tag((current_user.avatar_url.nil? ?  'default.jpg' : current_user.avatar_url), width: '50', height: '50', class: 'img-circle') %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "/auth/facebook" do %><%= image_tag('facebook.jpeg', width: '40', height: '40', class: 'img-circle') %><% end %></li>
        <% end %>
      </ul>

      </div>
    </div>
  </nav>

  <% flash.each do |key, value| %>
    <div class="alert alert-info"><%= value %></div>
  <% end %>

  <% if current_user %>
    <div class="text-container">
      <h1>Welcome, <%= current_user.name %></h1>
      <h4>Logged in with -> <strong><en><%= current_user.provider.capitalize %></strong></en></h4>
    </div>
  <% end %>

 <%= yield %>

  </body>
</html>

app/views/pay_cards/new.html.erb
<h1>New Card</h1>

<%= form_for :pay_card, url: pay_cards_new_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/_form.html.erb
<%= form_for current_user do |f| %>
  <% if current_user.errors.any? %>
    <div class="error_messages">
      <h2>Form invalid</h2>
      <ul>
        <% current_user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
 
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"> <%= f.submit %></div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>
 
<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/users/index.html.erb
<h1>Account Settings</h1>

<ul>
  <td><%= link_to 'Show', user_path(current_user.id) %></td>
  <td><%= link_to 'Edit', edit_user_path(current_user.id)%></td>
  <td><%= link_to 'Destroy', users_path(current_user.id),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/users/show.html.erb
<h1>Account:</h1>

<section>
      <p style="font-size: 28px;">
      <li> <%= current_user.email  %></li>
      </p>
</section>

 <%= link_to 'Edit', edit_user_path(current_user.id) %> 
 <%= link_to 'Back', root_url %>